name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        NEXT_PUBLIC_STRAPI_API_URL: https://eduokit-admin.herokuapp.com
        DOCKER_TAG: alpeza/eduoweb:latest
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
       echo $DOCKER_HUB_USERNAME | docker login --username alpeza --password-stdin;
       docker build . --file Dockerfile --tag "$DOCKER_TAG";
       docker push "$DOCKER_TAG"
